import rawBuildings from "../../../data/buildings.json";
import { BUILDING_IDS, type BuildingId, type BuildingState, type GameState, type NationalResources, type ProvinceId } from "./GameState";
export type ResourceDelta = Partial<Record<keyof NationalResources, number>>;
export interface BuildingDefinition { id:BuildingId; name:string; description:string; icon:string; tone:"gold"|"red"|"green"; maxLevel:number; maxInstances:number; constructionCost:ResourceDelta; constructionManpower:number; upgradeCost:ResourceDelta; upgradeManpower:number; monthlyProduction:ResourceDelta; monthlyUpkeep:ResourceDelta; }
type RawBuilding = { id:string; name:string; description:string; icon:string; tone:"gold"|"red"|"green"; max_level:number; max_instances?:number; construction_cost:ResourceDelta; construction_manpower?:number; upgrade_cost?:ResourceDelta; upgrade_manpower?:number; monthly_production:ResourceDelta; monthly_upkeep:ResourceDelta };
const rawBuildingList = rawBuildings.buildings as RawBuilding[];
function asBuildingId(id:string):BuildingId { if(!BUILDING_IDS.includes(id as BuildingId)) throw new Error(`Unknown building id: ${id}`); return id as BuildingId; }
export const BUILDING_DEFINITIONS:Record<BuildingId,BuildingDefinition> = Object.fromEntries(rawBuildingList.map(b=>[asBuildingId(b.id),{id:asBuildingId(b.id),name:b.name,description:b.description,icon:b.icon,tone:b.tone,maxLevel:b.max_level,maxInstances:b.max_instances ?? 10,constructionCost:b.construction_cost,constructionManpower:b.construction_manpower ?? 10,upgradeCost:b.upgrade_cost ?? b.construction_cost,upgradeManpower:b.upgrade_manpower ?? 10,monthlyProduction:b.monthly_production,monthlyUpkeep:b.monthly_upkeep}])) as Record<BuildingId,BuildingDefinition>;
export type BuildFailureReason = "game_ended"|"unknown_building"|"province_not_found"|"max_level"|"max_instances"|"insufficient_resources"|"insufficient_manpower";
export interface BuildCheck { ok:boolean; reason?:BuildFailureReason; cost:ResourceDelta; manpowerCost:number; nextLevel:number; instanceId?:string; definition?:BuildingDefinition; }
function hasResources(resources:NationalResources,cost:ResourceDelta){return Object.entries(cost).every(([k,v])=>resources[k as keyof NationalResources] >= (v ?? 0));}
export function getBuildingDefinition(id:BuildingId|string){return BUILDING_IDS.includes(id as BuildingId)?BUILDING_DEFINITIONS[id as BuildingId]:undefined;}
export function getBuildingInstances(buildings:BuildingState[],id:BuildingId,provinceId:ProvinceId="central"){return buildings.filter(b=>b.id===id&&b.provinceId===provinceId);}
export function canBuild(state:Pick<GameState,"resources"|"buildings"|"provinces"|"ending">,id:BuildingId,provinceId:ProvinceId="central",instanceId?:string):BuildCheck { const d=getBuildingDefinition(id); if(!d)return{ok:false,reason:"unknown_building",cost:{},manpowerCost:0,nextLevel:1}; if(state.ending)return{ok:false,reason:"game_ended",cost:{},manpowerCost:0,nextLevel:1,definition:d}; if(!state.provinces.some(p=>p.id===provinceId))return{ok:false,reason:"province_not_found",cost:{},manpowerCost:0,nextLevel:1,definition:d}; const instances=getBuildingInstances(state.buildings,id,provinceId); if(instanceId){const current=instances.find(b=>b.instanceId===instanceId); if(!current)return{ok:false,reason:"unknown_building",cost:{},manpowerCost:0,nextLevel:1,definition:d}; const next=current.level+1; if(next>d.maxLevel)return{ok:false,reason:"max_level",cost:{},manpowerCost:d.upgradeManpower,nextLevel:next,instanceId,definition:d}; const cost=Object.fromEntries(Object.entries(d.upgradeCost).map(([k,v])=>[k,(v??0)*next])) as ResourceDelta; if(!hasResources(state.resources,cost))return{ok:false,reason:"insufficient_resources",cost,manpowerCost:d.upgradeManpower,nextLevel:next,instanceId,definition:d}; if(state.resources.manpower<d.upgradeManpower)return{ok:false,reason:"insufficient_manpower",cost,manpowerCost:d.upgradeManpower,nextLevel:next,instanceId,definition:d}; return{ok:true,cost,manpowerCost:d.upgradeManpower,nextLevel:next,instanceId,definition:d}; } if(instances.length>=d.maxInstances)return{ok:false,reason:"max_instances",cost:{},manpowerCost:d.constructionManpower,nextLevel:1,definition:d}; if(!hasResources(state.resources,d.constructionCost))return{ok:false,reason:"insufficient_resources",cost:d.constructionCost,manpowerCost:d.constructionManpower,nextLevel:1,definition:d}; if(state.resources.manpower<d.constructionManpower)return{ok:false,reason:"insufficient_manpower",cost:d.constructionCost,manpowerCost:d.constructionManpower,nextLevel:1,definition:d}; return{ok:true,cost:d.constructionCost,manpowerCost:d.constructionManpower,nextLevel:1,instanceId:`${id}-${Date.now()}-${instances.length+1}`,definition:d}; }
export function buildBuilding(state:GameState,id:BuildingId,provinceId:ProvinceId="central",instanceId?:string):GameState { const check=canBuild(state,id,provinceId,instanceId); if(!check.ok||!check.definition)return state; const resources={...state.resources,manpower:state.resources.manpower-check.manpowerCost}; for(const[k,v]of Object.entries(check.cost))resources[k as keyof NationalResources]-=v??0; const buildings=[...state.buildings]; if(instanceId){const i=buildings.findIndex(b=>b.instanceId===instanceId); if(i>=0)buildings[i]={...buildings[i],level:check.nextLevel};} else buildings.push({instanceId:check.instanceId,id,provinceId,level:1}); return{...state,resources,buildings}; }
export const constructBuilding=buildBuilding;
export const upgradeBuilding=(state:GameState,id:BuildingId,instanceId:string,provinceId:ProvinceId="central")=>buildBuilding(state,id,provinceId,instanceId);
export function calculateBuildingResourceDelta(buildings:BuildingState[]):ResourceDelta { const delta:ResourceDelta={}; for(const b of buildings){const d=BUILDING_DEFINITIONS[b.id];if(!d||b.level<=0)continue;for(const[k,v]of Object.entries(d.monthlyProduction))delta[k as keyof NationalResources]=(delta[k as keyof NationalResources]??0)+(v??0)*b.level;for(const[k,v]of Object.entries(d.monthlyUpkeep))delta[k as keyof NationalResources]=(delta[k as keyof NationalResources]??0)-(v??0)*b.level;}return Object.fromEntries(Object.entries(delta).filter(([,v])=>v!==0)) as ResourceDelta; }
